<div class="page-header">
    <h1>Fill the form to register a new company</h1>
</div>
<div class="row">
    <div class="span12">
        <form action="/company/register" class="form-stacked" method="POST">
            <fieldset>
                <div class="clearfix">
                    <label for="name">Organization name:</label>

                    <div class="input">
                        <input id="name" name="name" type="text"/>
                    </div>
                </div>
                <div class="clearfix">
                    <label for="admin-name">Administrator name:</label>

                    <div class="input">
                        <input id="admin-name" name="admin-name" type="text"/>
                    </div>
                </div>
                <div class="clearfix">
                    <label for="admin-email">Administrator email:</label>

                    <div class="input"><input id="admin-email" name="admin-email" type="text"/></div>
                </div>
                <div class="clearfix">
                    <label for="password">Admin password:</b></label>

                    <div class="input"><input id="password" name="password" type="password"/></div>
                </div>
                <div class="clearfix">
                    <label for="confirm-password">Confirm password:</label>

                    <div class="input"><input id="confirm-password" name="confirm-password" type="password"/></div>
                </div>
                <div class="clearfix">
                    <label for="subscription-plan">Choose a subscription plan:</label>
                    <? // TODO: subscriptions list scenario ?>
                    <div class="input">
                        <select name="subscription-plan" id="subscription-plan">
                            <option value="1">Standard</option>
                            <option value="2">Pro</option>
                        </select>
                    </div>
                </div>
                <div class="actions">
                    <input type="submit" class="btn primary" value="Register"/>
                </div>
            </fieldset>
        </form>
    </div>
</div>
