<?
    // Preparing some current session data
    $companyName = $this->session->getUser()->getCompany()->getName();
    $loginedAs = $this->session->getUser()->getEmail();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <? // TODO: common header for all layouts ?>
    <meta charset="utf-8">
    <title>BasicCRM</title>
    <meta name="description" content="Description can be found at blog.lcf.name">
    <meta name="author" content="Alexander Steshenko">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
    <script src="http://twitter.github.com/bootstrap/1.4.0/bootstrap-dropdown.js"></script>
    <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>
</head>
<? //TODO: refactor views, remove repetitions ?>
<body>
<div class="topbar-wrapper" style="z-index: 5;">
    <div class="topbar">
        <div class="fill">
            <div class="container">
                <a class="brand" href="#">BasicCRM for <?= $companyName ?></a>
                <ul class="nav">
                    <li class="active"><a href="/company/dashboard">Dashboard</a></li>
                    <li><a href="/index/about">About BasicCrm</a></li>
                    <li><a href="http://lcf.name" target="_blank">Contact</a></li>
                </ul>
                <ul class="nav secondary-nav">
                    <li class="dropdown" data-dropdown="dropdown">
                        <a href="#" class="dropdown-toggle">Signed in as <?= $loginedAs ?></a>
                        <ul class="dropdown-menu">
                            <li><a href="/auth/logout">Sign out</a></li>
                            <!--                <li class="divider"></li>-->
                            <!--                <li><a href="#">Another link</a></li>-->
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div class="sidebar">
            <ul>
                <li><a href="#">View users</a></li>
                <li><a href="#">Add new user</a></li>
                <li><a href="#">Manage clients</a></li>
            </ul>
        </div>
        <div class="content"><?= $this->layout()->content ?></div>
    </div>
</div>
</body>
</html>