<?
// Preparing some current session data
// NOTE: if we used DTOs "session data" would be currently logged in user and their company information.
$companyName = $this->session->getUser()->getCompany()->getName();
$isAdmin = $this->session->getUser()->isAdmin();
$loginedAs = $this->session->getUser()->getEmail();
?>
<!DOCTYPE html>
<html lang="en">
<?= $this->render('layout-header.phtml') ?>
<body>
<div class="topbar-wrapper" style="z-index: 5;">
    <div class="topbar">
        <div class="fill">
            <div class="container">
                <a class="brand" href="#">BasicCRM for <?= $companyName ?></a>
                <ul class="nav">
                    <li class="active"><a href="/company/dashboard">Dashboard</a></li>
                    <li><a href="/index/about">About BasicCrm</a></li>
                    <li><a href="http://lcf.name" target="_blank">Contact</a></li>
                </ul>
                <ul class="nav secondary-nav">
                    <li class="dropdown" data-dropdown="dropdown">
                        <a href="#" class="dropdown-toggle">Signed in as <?= $loginedAs ?></a>
                        <ul class="dropdown-menu">
                            <li><a href="/auth/logout">Sign out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div class="sidebar">
            <? if ($isAdmin) : ?>
            <ul>
                <? // Admin only actions listed here ?>
                <li><a href="/company/add-user"><strong>Add new user</strong></a></li>
                <li><a href="/company/switch-admin"><strong>Switch administrator</strong></a></li>
            </ul>
            <? endif ?>
            <ul>
                <li><a href="/company/users">View colleagues</a></li>
                <li><a href="/auth/change-password">Change password</a></li>
                <li><a href="/company/clients">Manage clients</a></li>
            </ul>
        </div>
        <div class="content"><?= $this->layout()->content ?></div>
    </div>
</div>
</body>
</html>