<!DOCTYPE html>
<html lang="en">
<?= $this->render('layout-header.phtml') ?>
<body>
<div class="topbar-wrapper" style="z-index: 5;">
    <div class="topbar">
        <div class="fill">
            <div class="container">
                <a class="brand" href="#">BasicCRM</a>
                <ul class="nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="/index/about">About</a></li>
                    <li><a href="http://lcf.name" target="_blank">Contact</a></li>
                </ul>
                <form action="/auth/login" method="POST" class="pull-right">
                    <input class="input-small" type="text" placeholder="Email" name="email"/>
                    <input class="input-small" type="password" placeholder="Password" name="password"/>
                    <button class="btn" type="submit">Sign in</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div class="sidebar">
            <ul>
                <li><a href="/company/register">Sign up</a></li>
                <li><a href="/auth/login">Sign in</a></li>

            </ul>
        </div>
        <div class="content"><?= $this->layout()->content ?></div>
    </div>
</div>
</body>
</html>