<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>BasicCRM</title>
<link rel="stylesheet" type="text/css" href="/css/main.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/css/print.css" media="print" />
<!--[if lte IE 6]>
<link rel="stylesheet" type="text/css" href="/css/ie6_or_less.css" />
<![endif]-->
</head>
<body id="type-b">
<div id="wrap">
	<div id="header">
		<div id="site-name">BasicCRM</div>
		<ul id="nav">
		<li class="first"><a href="/">Home</a></li>
		<li class="last"><a href="#">About</a>
			<ul>
			<li class="first"><a href="http://blog.lcf.name">Underground Programming Blog</a></li>
			<li class="last"><a href="http://lcf.name">LCF.NAME</a></li>
			</ul>
		</li>
		</ul>
	</div>
	
	<div id="content-wrap">
		<div id="utility">
    		<ul id="nav-secondary">
			<li class="first"><a href="/company/register">Register a new company</a></li>
			</ul>
		</div>
		
		<div id="content">
            <?= $this->layout()->content ?>
			<div id="footer">
			<p>Demo DDD web application for the series of articles</p>
			<p><a href="http://blog.lcf.name">Underground Programming Blog</a> | <a href="http://lcf.name">LCF.NAME</a></p>
			</div>
		</div>
	</div>
</div>
</body>
</html>