<?= $this->pageHeader('About BasicCRM') ?>
<p>BasicCRM is a simple Customer Relationship Management tool which helps you and your team to organize work
    with your clients and tasks related to them.</p>

<p>While you may use the CRM if you think it fits your needs it is not a real-world application, but a
    demonstration application being developed specifically for a series of articles in the <a
            href="http://blog.lcf.name" target="_blank">Underground
        Programming Blog</a>
</p>

<p>The series illustrates how you can build a PHP application using Domain Driven Design approach, when you
    write code according to the business rules
    and try to make the infrastructure not affect the logic so much. Please, read the details in the
    blog.</p>