<?= $this->pageHeader('Change password') ?>
<p>
Once the password is change you will no longer be able to login with the previous one.
</p>
<div class="row">
    <div class="span12">
        <form action="/auth/change-password" class="form-stacked" method="POST">
            <fieldset>
                <div class="clearfix">
                    <label for="password">Your current password:</b></label>

                    <div class="input"><input id="password" name="password" type="password"/></div>
                </div>
                <div class="clearfix">
                    <label for="new-password">New password:</b></label>

                    <div class="input"><input id="new-password" name="new-password" type="password"/></div>
                </div>
                <div class="clearfix">
                    <label for="confirm-new-password">Confirm new password:</b></label>

                    <div class="input"><input id="confirm-new-password" name="confirm-new-password" type="password"/></div>
                </div>
                <div class="actions">
                    <input type="submit" class="btn primary" value="Change"/>
                </div>
            </fieldset>
        </form>
    </div>
</div>

