<form action="/auth/login" method="POST" class="f-wrap-1">
    <fieldset>
    <h3>Fill the form to login</h3>
    <label for="email"><b>Email:</b>
        <input id="email" name="email" type="text" class="f-email" tabindex="1" /><br />
    </label>
    <label for="password"><b>Password:</b>
        <input id="password" name="password" type="password" class="f-name" tabindex="2" /><br />
    </label>
    <div class="f-submit-wrap">
        <input type="submit" value="Login" class="f-submit" tabindex="3" /><br />
    </div>
    </fieldset>
</form>

