<div class="page-header">
    <h1>Fill the form to sign in</h1>
</div>
<div class="row">
    <div class="span12">
        <form action="/auth/login" method="POST">
            <fieldset>
                <div class="clearfix">
                    <label for="email">Email:</label>

                    <div class="input">
                        <input id="email" name="email" type="text"/></div>
                </div>


                <div class="clearfix">
                    <label for="password">Password:</label>

                    <div class="input">
                        <input id="password" name="password" type="password"/>
                    </div>
                </div>
                <div class="actions">
                    <input type="submit" class="btn primary" value="Sign in"/>
                </div>
            </fieldset>
        </form>
    </div>
</div>

