<head>
    <meta charset="utf-8">
    <title>BasicCRM</title>
    <meta name="description" content="Description can be found at blog.lcf.name">
    <meta name="author" content="Alexander Steshenko">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
    <script src="/bootstrap-1.4.0/bootstrap-dropdown.js"></script>
    <link rel="stylesheet" href="/bootstrap-1.4.0/bootstrap.css">
    <style type="text/css">body {padding-top: 60px;}</style>
</head>
