<?php

namespace Infrastructure\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DomainCompanyProxy extends \Domain\Company implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getAdmin()
    {
        $this->__load();
        return parent::getAdmin();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getConfirmationCode($salt)
    {
        $this->__load();
        return parent::getConfirmationCode($salt);
    }

    public function isActivated()
    {
        $this->__load();
        return parent::isActivated();
    }

    public function activate($confirmationCode, $salt)
    {
        $this->__load();
        return parent::activate($confirmationCode, $salt);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'subscription', 'isActivated', 'users');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}