<?php

namespace Infrastructure\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DomainUserProxy extends \Domain\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function isPasswordValid($password)
    {
        $this->__load();
        return parent::isPasswordValid($password);
    }

    public function isActivated()
    {
        $this->__load();
        return parent::isActivated();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function isAdmin()
    {
        $this->__load();
        return parent::isAdmin();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function revokeAdmin()
    {
        $this->__load();
        return parent::revokeAdmin();
    }

    public function grantAdmin()
    {
        $this->__load();
        return parent::grantAdmin();
    }

    public function getCompany()
    {
        $this->__load();
        return parent::getCompany();
    }

    public function setCompany(\Domain\Company $company)
    {
        $this->__load();
        return parent::setCompany($company);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'email', 'passwordHash', 'isAdmin', 'company');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}